//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int c_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public string pt_id { get; set; }
        public string pf_id { get; set; }
        public string pa_id { get; set; }
        public string pm_id { get; set; }
    
        public virtual PetAccessory PetAccessory { get; set; }
        public virtual PetFood PetFood { get; set; }
        public virtual PetMedicine PetMedicine { get; set; }
        public virtual PetToy PetToy { get; set; }
        public virtual User User { get; set; }
    }
}
