//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentDetail
    {
        public Nullable<int> cmt_id { get; set; }
        public int cmtd_id { get; set; }
        public string cmtd_content { get; set; }
        public Nullable<System.DateTime> cmtd_published { get; set; }
        public string cmtd_status { get; set; }
        public Nullable<int> u_id { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
    }
}
