//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Drawing;
    using System.IO;

    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.Comments = new HashSet<Comment>();
        }
        public static string path = @"..\..\img\";
        public string p_id { get; set; }
        public string p_name { get; set; }
        public int p_prices { get; set; }
        public int p_salePrice { get; set; }
        public string p_image { get; set; }
        [NotMapped]
        public Image Picture
        {
            get
            {
                if (!string.IsNullOrEmpty(path + p_image))
                {
                    if (File.Exists(path + p_image))
                    {
                        return Image.FromFile(path + p_image);
                    }
                }
                return null;
            }
        }
        public string p_description { get; set; }
        public Nullable<System.DateTime> p_published { get; set; }
        public string p_status { get; set; }
        public Nullable<int> t_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Type Type { get; set; }
    }
}
